---
config:
  theme: redux
---
erDiagram
    SlipSize {
        INT sizeFt PK
    }

    WaitList {
        INT waitListID PK
        INT boatID FK
        INT sizeFt FK
        TIMESTAMP timeJoined
        TIMESTAMP timeClosed
        STRING status
    }

    SlipSize ||--o{ WaitList : requestedFor