package com.moffatbaymarina.marinawebsite.dao;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import com.moffatbaymarina.marinawebsite.model.Boat;

/**
 * Data access object for the {@code Boat} and {@code BoatOwnership}
 * database tables.
 * Ai assisted with JavaDoc comments in this file.
 * @author Carolina Rodriguez
 */
public class BoatDAO {

        /**
         * Inserts a boat record.
         *
         * @param conn active transaction connection
         * @param boat boat being registered
         * @throws SQLException if the insert fails
         */
    public int insertBoat(Connection conn, Boat boat) throws SQLException {

        String sql = """
                INSERT INTO Boat (
                    boatName,
                    regNumber,
                    boatLength,
                    HIN,
                    boatType,
                    boatBeam,
                    boatYear
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """;

        //Insert the boat and request the generated primary key.--------------------------------------------------------------

        try (PreparedStatement stmt = conn.prepareStatement(
                sql,
                Statement.RETURN_GENERATED_KEYS)) {

        //Map the boat model values to the SQL parameters-------------------------------------------------------------------

            stmt.setString(1, boat.getBoatName());
            setNullableString(stmt, 2, boat.getRegNumber());
            stmt.setBigDecimal(3, boat.getBoatLength());
            setNullableString(stmt, 4, boat.getHIN());
            setNullableString(stmt, 5, boat.getBoatType());
            setNullableDecimal(stmt, 6, boat.getBoatBeam());
            setNullableInteger(stmt, 7, boat.getBoatYear());

            if (stmt.executeUpdate() != 1) {
                throw new SQLException(
                        "Boat registration did not insert one row.");
            }
            //Return the BoatID generated by the database 

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
            }

            throw new SQLException(
                    "Boat registration did not return a boatID.");
        }
    }
    //Customer and boat ownership----------------------------------------------------------------------------------------
    /**
     * Connects a boat to a customer through BoatOwnership table.
     *
     * @param conn active transaction connection
     * @param boatId the ID of the boat being registered
     * @param customerId the ID of the customer who owns the boat
     * @throws SQLException if the insert fails
    */

    public void insertOwnership(
		Connection conn,
		int boatId,
		int customerId) throws SQLException {

	String sql = """
			INSERT INTO BoatOwnership (
				boatID,
				customerID,
				startDate,
				endDate
			)
			VALUES (?, ?, CURRENT_DATE, NULL)
			""";

	try (PreparedStatement stmt = conn.prepareStatement(sql)) {
		stmt.setInt(1, boatId);
		stmt.setInt(2, customerId);

		if (stmt.executeUpdate() != 1) {
			throw new SQLException(
					"Boat ownership did not insert one row.");
		}
	}
}

    /**
     * Returns  all boats currently owned by a customer. Reservation-only
     * derived values (slip size and monthly cents) are filled by the servlet;
     * checks active-reservation status for dropdown menu to prevent
     * duplicate reservations for the same boat
     */
    public List<Boat> findByCustomerId(Connection conn, int customerId)
            throws SQLException {
        String sql = """
                SELECT b.boatID, b.boatName, b.boatLength,
                       EXISTS (SELECT 1 FROM Reservation r 
                       WHERE r.boatID = b.boatID
                       AND r.reservationStatus = 'Active') 
                       AS hasActiveReservation 
                FROM Boat b
                JOIN BoatOwnership bo ON bo.boatID = b.boatID
                WHERE bo.customerID = ? AND bo.endDate IS NULL
                ORDER BY b.boatName
                """;

        List<Boat> boats = new ArrayList<>();
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, customerId);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    boats.add(mapReservationBoat(rs));
                }
            }
        }
        return boats;
    }


    private Boat mapReservationBoat(ResultSet rs) throws SQLException {
        Boat boat = new Boat();
        boat.setBoatId(rs.getInt("boatID"));
        boat.setBoatName(rs.getString("boatName"));
        boat.setBoatLength(rs.getBigDecimal("boatLength"));
        boat.setHasActiveReservation(rs.getBoolean("hasActiveReservation"));
        return boat;
    }




	//Nullable SQL parameter helpers-----------------------------------------------------------------------------------

	private void setNullableString(
			PreparedStatement stmt,
			int index,
			String value) throws SQLException {

		if (value == null || value.isBlank()) {
			stmt.setNull(index, Types.VARCHAR);
		} else {
			stmt.setString(index, value);
		}
	}

	private void setNullableDecimal(
			PreparedStatement stmt,
			int index,
			BigDecimal value) throws SQLException {

		if (value == null) {
			stmt.setNull(index, Types.DECIMAL);
		} else {
			stmt.setBigDecimal(index, value);
		}
	}

	private void setNullableInteger(
			PreparedStatement stmt,
			int index,
			Integer value) throws SQLException {

		if (value == null) {
			stmt.setNull(index, Types.INTEGER);
		} else {
			stmt.setInt(index, value);
		}
	}
}