package com.moffatbaymarina.marinawebsite.dao;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Types;
import java.sql.ResultSet;
import java.sql.Statement;

import com.moffatbaymarina.marinawebsite.model.Boat;

/**
 * Data access object for the {@code Boat} and {@code BoatOwnership}
 * database tables.
 * Ai assisted with JavaDoc comments in this file.
 * @author Carolina Rodriguez
 */
public class BoatDAO {

        /**
         * Inserts a boat record.
         *
         * @param conn active transaction connection
         * @param boat boat being registered
         * @throws SQLException if the insert fails
         */
    public int insertBoat(Connection conn, Boat boat) throws SQLException {

        String sql = """
                INSERT INTO Boat (
                    boatName,
                    regState,
                    regNumber,
                    boatLength,
                    HIN,
                    boatType,
                    boatBeam,
                    boatYear
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """;

        //Insert the boat and request the generated primary key.--------------------------------------------------------------

        try (PreparedStatement stmt = conn.prepareStatement(
                sql,
                Statement.RETURN_GENERATED_KEYS)) {

        //Map the boat model values to the SQL parameters-------------------------------------------------------------------

            stmt.setString(1, boat.getBoatName());
            setNullableString(stmt, 2, boat.getRegState());
            setNullableString(stmt, 3, boat.getRegNumber());
            stmt.setBigDecimal(4, boat.getBoatLength());
            setNullableString(stmt, 5, boat.getHIN());
            setNullableString(stmt, 6, boat.getBoatType());
            setNullableDecimal(stmt, 7, boat.getBoatBeam());
            setNullableInteger(stmt, 8, boat.getBoatYear());

            if (stmt.executeUpdate() != 1) {
                throw new SQLException(
                        "Boat registration did not insert one row.");
            }
            //Return the BoatID generated by the database 

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
            }

            throw new SQLException(
                    "Boat registration did not return a boatID.");
        }
    }
    //Customer and boat ownership----------------------------------------------------------------------------------------
    /**
     * Connects a boat to a customer through BoatOwnership table.
     *
     * @param conn active transaction connection
     * @param boatId the ID of the boat being registered
     * @param customerId the ID of the customer who owns the boat
     * @throws SQLException if the insert fails
    */

    public void insertOwnership(
		Connection conn,
		int boatId,
		int customerId) throws SQLException {

	String sql = """
			INSERT INTO BoatOwnership (
				boatID,
				customerID,
				startDate,
				endDate
			)
			VALUES (?, ?, CURRENT_DATE, NULL)
			""";

	try (PreparedStatement stmt = conn.prepareStatement(sql)) {
		stmt.setInt(1, boatId);
		stmt.setInt(2, customerId);

		if (stmt.executeUpdate() != 1) {
			throw new SQLException(
					"Boat ownership did not insert one row.");
		}
	}
}
	//Nullable SQL parameter helpers-----------------------------------------------------------------------------------

	private void setNullableString(
			PreparedStatement stmt,
			int index,
			String value) throws SQLException {

		if (value == null || value.isBlank()) {
			stmt.setNull(index, Types.VARCHAR);
		} else {
			stmt.setString(index, value);
		}
	}

	private void setNullableDecimal(
			PreparedStatement stmt,
			int index,
			BigDecimal value) throws SQLException {

		if (value == null) {
			stmt.setNull(index, Types.DECIMAL);
		} else {
			stmt.setBigDecimal(index, value);
		}
	}

	private void setNullableInteger(
			PreparedStatement stmt,
			int index,
			Integer value) throws SQLException {

		if (value == null) {
			stmt.setNull(index, Types.INTEGER);
		} else {
			stmt.setInt(index, value);
		}
	}
}